# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c61e7e1c8732b80a67c368e16660e1dc33607ddc2fd70f64a4756a4515fc5efbee1db26707a1c4b08f9c72a64796f2fa8eb294d0e913044318f0c21e2325cb9a

test:
  secret_key_base: 1f70429eaecfe7350bfe8eff6661e4bd67851e891b1add9fdcb79fa394a31e7626e66b63620241e506f63c33171ec6cdec537be4b9ef0523070a5249f0479b7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
